"""empty message

Revision ID: 165620f49888
Revises: 1f8e16e354c8
Create Date: 2018-04-27 17:22:51.924580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165620f49888'
down_revision = '1f8e16e354c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Follows')
    op.drop_table('Posts')
    op.drop_table('user_profiles')
    op.drop_table('Likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Likes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Likes_id_seq"\'::regclass)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Likes_pkey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('joined_on', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_profiles_pkey')
    )
    op.create_table('Posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Posts_id_seq"\'::regclass)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Posts_pkey')
    )
    op.create_table('Follows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Follows_id_seq"\'::regclass)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Follows_pkey')
    )
    # ### end Alembic commands ###
